#
# Build
#

FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./

RUN go build -o /Tutor

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /
COPY --from=build /Tutor /Tutor
EXPOSE 9044
USER nonroot:nonroot

ENTRYPOINT ["/Tutor"]
