DROP DATABASE IF EXISTS ETIAssignment2TestDB;

CREATE DATABASE ETIAssignment2TestDB;

USE ETIAssignment2TestDB;

DROP TABLE IF EXISTS Student;
CREATE TABLE Student(
	StudentID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name varchar(255) NOT NULL);
    
DROP TABLE IF EXISTS Tutor;
CREATE TABLE Tutor(
	TutorID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name varchar(255) NOT NULL);

DROP TABLE IF EXISTS Class;
CREATE TABLE Class(
	ClassID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name varchar(255) NOT NULL);
    
DROP TABLE IF EXISTS Module;
CREATE TABLE Module(
	ModuleID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name varchar(255) NOT NULL);